### ISSUE TITLE
Lox model walls

### ISSUE THREAD

**Issue by apgeo** [aardgoose/CaveView.js#3]
Hello,

This is a really cool library. Looking forward to work with it.

On preliminary testing, it seems like the viewer does not display walls for models loaded from Lox files. It doesn't display the terrain (embedded in Lox files) either. Have tested with my files (which have both terrain and 3D wall passages defined when viewing with Loch) and have seen this on https://aardgoose.github.io/CaveView.js/fulldemo.html when loading "Cheddar.lox" as well. If needed, will send test files.

Do you know about this behavior?

Thanks

**Comment by aardgoose** [comment]
Hi Thanks,

I have brought back loading terrain data and overlay images, you can see that on the cheddar.lox demo.
This was removed while adding support for background loading of surveys.
 
I can't remember why I didn't add walls rendered from cross section info, rather than from scraps, I was probably making sure cross sections worked for survex .3d models, and never returned to .lox support.

I'll take a look at it,

**Comment by aardgoose** [comment]
Basic walls based in LRUD data now rendered.

This doesn't support the range of passage shapes that loch does.

@apgeo if you have any examples with varying passage shapes, I can take a look at more complex modelling,
